In [2]:
import pandas as pd
import numpy as np
from sklearn import datasets
import scipy as sc

In [170]:
class MyLRGD:

    def __init__(self,learning_rate=0.3,max_iterations=1000) -> None:
        self.n = learning_rate
        self.iter = max_iterations
        self.W = None
        self.coef_ = None
        self.bias = None

    def intialize_weights(self,input_data):
        return np.random.uniform(0,1,input_data.shape[1])

    def fit(self,X,y):
        X_b = np.insert(X,0,1,axis=1)
        self.W = self.intialize_weights(X_b)
        for _ in range(self.iter):
            y_hat = np.dot(X_b,self.W)
            error = y_hat-y
            grad = X_b.T.dot(error)/y.shape[0]
            self.W = self.W - self.n*grad
        self.coef_ = self.W[1:]
        self.bias = self.W[0]

    def predict(self,X):
        return self.W.dot(np.insert(X,0,1,axis=1).T)

In [171]:
data = datasets.load_diabetes()
diab_data = pd.DataFrame(data = data['data'], columns = data['feature_names'])
diab_data['target'] = data['target']
diab_data

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019907 -0.017646   151.0  
1   -0.039493 -0.068332 -0.092204    75.0  
2   -0.002592  0.002861 -0.025930   141.0  
3    0.034309  0.022688 -0.009362   206.0  
4   -0.002592 -0.031988 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018114  0.044485   104.0  
439 -0.011080 -0.046883  0.015491   132.0  
440  0.026560  0.044529 -0.025930   220.0  
441 -0.039493 -0.004222  0.003064    57.0  

[442 rows x 11 columns]

In [172]:
X=diab_data.drop(columns=['target'])
y=diab_data['target']

In [173]:
from sklearn.model_selection import train_test_split

In [174]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8,random_state=42)

In [175]:
obj = MyLRGD(max_iterations=125)
obj.fit(X_train,y_train)

In [176]:
obj.W

array([153.30588216,  22.58814036,  -1.22131554,  75.7453416 ,
        56.01472163,  21.24715312,  15.69883884, -45.08960085,
        49.80948948,  68.38632703,  47.0671715 ])

In [149]:
obj.predict(X_test)

array([160.3968512 , 154.08320723, 158.73282025, 185.78196251,
       154.72609017, 149.33604428, 174.3646503 , 170.66870152,
       142.0845737 , 150.3461717 , 142.91106559, 146.61985379,
       128.60616022, 170.24901561, 145.6827712 , 146.81872407,
       172.61956517, 177.64546572, 153.01319707, 168.7790357 ,
       157.01841559, 143.49696246, 136.12469916, 163.70563626,
       148.66459493, 157.30469001, 159.94556845, 158.90024676,
       128.00874908, 153.03435624, 158.83699198, 140.61344706,
       152.16734191, 162.49170311, 161.9854972 , 163.93754921,
       151.5503728 , 154.64858406, 162.22899571, 132.87756574,
       139.67742911, 147.24755837, 152.26110463, 161.70097913,
       157.51080348, 134.71940878, 135.30534737, 137.46656366,
       131.49543089, 148.84496806, 143.35708285, 131.93899192,
       151.08202559, 143.09532766, 166.43290916, 146.5634253 ,
       145.21437815, 160.83275286, 141.9936808 , 130.15220597,
       164.75625023, 156.15506169, 146.81130539, 148.73

In [111]:
from sklearn.linear_model import LinearRegression

In [112]:
lr = LinearRegression()

lr.fit(X_train,y_train)
lr.predict(X_test)

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59